name: test

on:
  push:
    branches: [ main ]

jobs:
  do-something:
    runs-on: ubuntu-latest
    container:
      image: pandoc/core:latest-ubuntu
      options: --entrypoint=sh
    steps:
      - name: NAME-01 ... Installiere make
        run: |
          apt update
          apt install make -y
      - name: NAME-02 ...
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: NAME-03 ...
        run: |
          ls -la
          mkdir Ablage
      - name: NAME-04 ...
        run: |
          pandoc test.md -s --to html5 -o Ablage/test.html
          pandoc test.md -o Ablage/test.odt
          pandoc test.md -o Ablage/test.docx
      - name: NAME-05 ... Datei zum internen Download bereitstellen ...
        uses: actions/upload-artifact@v2
        with:
          name: Blablubber
          path: Ablage/
      - name: TEST
        run: ls -la
      - name: TEST2
        run: make WITH_ATS=1
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)
      - name: Update changes in GitHub repository
        if: steps.git-check.outputs.modified == 'true'
        run:  |
          git config --global user.name 'maybegeek' 
          git config --global user.email 'chr.pfeiffer@gmail.com'
          git add -A
          git commit -m '[automated commit] add configs generated using jsonnet & GitHub workflow'
          git push
