name: test

on:
  push:
    branches: [ main ]

jobs:
  do-something:
    runs-on: ubuntu-latest
    container:
      image: pandoc/core:latest-ubuntu
      options: --entrypoint=sh
    steps:
      - name: NAME-01 ... Installiere make
        run: |
          apt update
          apt install make git -y
      - name: NAME-02 ...
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: TEST2
        run: make WITH_ATS=1
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)
      - name: Update changes in GitHub repository
        if: steps.git-check.outputs.modified == 'true'
        run:  |
          git config --global user.name 'maybegeek' 
          git config --global user.email 'chr.pfeiffer@gmail.com'
          git add -A
          git commit -m '[automated commit] GitHub workflow with pandoc and Makefile'
          git push
