name: test

on:
  push:
    branches: [ main ]

jobs:
  do-something:
    runs-on: ubuntu-latest
    container:
      image: pandoc/core:latest-ubuntu
      options: --entrypoint=sh
    steps:
      - name: NAME-01 ... Installiere make
        run: |
          apt-get update
          apt-get install make git rsync locale-gen update-locale -y
          locale-gen de_DE.UTF-8
          update-locale LANG=de_DE.UTF-8
      - name: NAME-02 ...
        uses: actions/checkout@master
        with:
          fetch-depth: 2
      - name: NAME-03 ... TEST2
        run: make GITACT=1
      - name: NAME-04 ... Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)
      - name: Reuse message
        run: |
          echo 'COMMIT_MSG<<EOM' >> "$GITHUB_ENV"
          git log -n1 --pretty='%B' >> "$GITHUB_ENV"
          echo 'EOM' >> "$GITHUB_ENV"
      - name: blaaaa
        if: steps.git-check.outputs.modified == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: ${{ env.COMMIT_MSG }}
          commit_options: --amend --no-edit
          push_options: --force
          skip_fetch: true
