name: test

on:
  push:
    branches: [ main ]

jobs:
  do-something:
    runs-on: ubuntu-latest
    container:
      image: docker://pandoc/latex:2.9
      options: --entrypoint=sh
    steps: 
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Blablubbb
        run: ls -la
      - name: sdfsdf
        run: apt-get install make -y          