name: test

on:
  push:
    branches: [ main ]

jobs:
  do-something:
    runs-on: ubuntu-latest
    container:
      image: pandoc/core:latest-ubuntu
      options: --entrypoint=sh
    steps:
      - name: STEP-01 ... Installiere make
        run: |
          apt update
          apt install make -y
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Blablubbb
        run: |
          ls -la
          mkdir Ablage
      - name: Sachen machen
        run: |
          pandoc test.md -s --to html5 -o Ablage/test.html
          pandoc test.md -o Ablage/test.odt
          pandoc test.md -o Ablage/test.docx
      - uses: actions/upload-artifact@v2
        with:
          name: output
          path: output
          
      - name: Datei zum internen Download bereitstellen ...
        uses: actions/upload-artifact@v2
        with:
          name: Blablubber
          path: Ablage
