name: test

on:
  push:
    branches: [ main ]

jobs:
  do-something:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Blablubbb
        run: ls -la
      - name: zeug
        uses: docker://pandoc/core:2-ubuntu
      - name: install make
        run: sudo apt-get install make -y
      - name:
        run: ls -la
          